### ISSUE TITLE
dump tests failure: missing m2m field data?

### ISSUE THREAD

**Issue by xrmx** [xrmx/django-denis#5]
It looks like we load the m2m middle table but we don't load the second leg of the m2m relationship, in this case testdenis.EvenMoreData;

```
PROCESSING testdenis.somedata
Installed 1 object(s) from 1 fixture(s)
PROCESSING testdenis.somedata_evenmore
Traceback (most recent call last):
  File "/home/rm/src/django-denis/test_django_denis/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/loaddata.py", line 61, in handle
    self.loaddata(fixture_labels)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/loaddata.py", line 97, in loaddata
    connection.check_constraints(table_names=table_names)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 454, in check_constraints
    referenced_table_name, referenced_column_name))
django.db.utils.IntegrityError: Problem installing fixtures: The row in table 'testdenis_somedata_evenmore' with primary key '1' has an invalid foreign key: testdenis_somedata_evenmore.evenmoredata_id contains a value '1' that does not have a corresponding value in testdenis_evenmoredata.id.
PROCESSING testdenis.somemoredata
Installed 1 object(s) from 1 fixture(s)
```

**Comment by xrmx** [comment]
This has been killed in 1fe12b313bf1f51d7ca06268883ca73fa2c31aa0 . No code no issues.
